apiVersion: v2
name: engine-woo
description: A wrapper chart for WooCommerce
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: wordpress
    version: 19.1.5
    repository: https://charts.bitnami.com/bitnami