wordpress:
  image: wordpress:6.4-apache
  username: admin
  password: password # Operator will override this
  email: user@example.com

mysql:
  image: mysql:5.7
  rootPassword: rootpassword # Operator will override this
  database: wordpress
  username: wordpress
  password: wordpress # Operator will override this

ingress:
  enabled: true
  className: nginx
  host: store.local # Operator will override this