# 1. Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: store-operator-sa
  namespace: default
---
# 2. ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: store-operator-role
rules:
  - apiGroups: ["infra.store.io"]
    resources: ["stores", "stores/status", "stores/finalizers"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: [""]
    resources:
      - namespaces
      - services
      - pods
      - events
      - persistentvolumeclaims
      - secrets
      - configmaps
      - resourcequotas
      - limitranges
      - serviceaccounts
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies", "ingresses"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources:
      - roles
      - rolebindings
    verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
# 3. ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: store-operator-binding
subjects:
  - kind: ServiceAccount
    name: store-operator-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: store-operator-role
  apiGroup: rbac.authorization.k8s.io
---
# 4. Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store-operator
  template:
    metadata:
      labels:
        app: store-operator
    spec:
      serviceAccountName: store-operator-sa
      containers:
        - name: manager
          image: ghcr.io/jovial-kanwadia/store-operator:latest
          imagePullPolicy: Always
          env:
            - name: WORDPRESS_CHART_PATH
              value: "/charts/engine-woo"
            - name: BASE_DOMAIN
              value: "165.22.215.118.nip.io"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
